import { Tool } from '../types/index.ts';

export const TOOLS_DB: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    description: 'Advanced AI language model for conversation, coding, and content creation.',
    websiteUrl: 'https://chat.openai.com',
    imageUrl: 'https://picsum.photos/seed/chatgpt/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Chat', 'Writing', 'Coding'],
    freeAlternative: { name: 'Claude', url: 'https://claude.ai' },
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'High-quality AI image generation from natural language descriptions.',
    websiteUrl: 'https://www.midjourney.com',
    imageUrl: 'https://picsum.photos/seed/midjourney/400/200',
    category: 'Image Generation',
    pricingModel: 'Paid',
    tags: ['Art', 'Design', 'Images', 'YouTube Thumbnail', 'Thumbnail'],
    freeAlternative: { name: 'Stable Diffusion', url: 'https://stability.ai' },
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that helps you write code faster with less work.',
    websiteUrl: 'https://github.com/features/copilot',
    imageUrl: 'https://picsum.photos/seed/copilot/400/200',
    category: 'Coding',
    pricingModel: 'Paid',
    tags: ['Programming', 'Development', 'AI'],
    freeAlternative: { name: 'Codeium', url: 'https://codeium.com' },
  },
  {
    id: '4',
    name: 'Jasper',
    description: 'AI content platform that helps teams create high-quality content faster.',
    websiteUrl: 'https://www.jasper.ai',
    imageUrl: 'https://picsum.photos/seed/jasper/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Marketing', 'Writing', 'Business'],
    freeAlternative: { name: 'Copy.ai', url: 'https://www.copy.ai' },
  },
  {
    id: '5',
    name: 'Luma Dream Machine',
    description: 'Generate high-quality, realistic videos from text and images.',
    websiteUrl: 'https://lumalabs.ai/dream-machine',
    imageUrl: 'https://picsum.photos/seed/luma/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Animation', 'AI'],
    freeAlternative: { name: 'Kling AI', url: 'https://klingai.com' },
  },
  {
    id: '6',
    name: 'ElevenLabs',
    description: 'The most realistic AI speech software, perfect for creators and publishers.',
    websiteUrl: 'https://elevenlabs.io',
    imageUrl: 'https://picsum.photos/seed/elevenlabs/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Voice', 'Audio', 'TTS'],
    freeAlternative: { name: 'Speechify', url: 'https://speechify.com' },
  },
  {
    id: '7',
    name: 'Claude',
    description: 'Next-generation AI assistant for your tasks, no matter the scale.',
    websiteUrl: 'https://claude.ai',
    imageUrl: 'https://picsum.photos/seed/claude/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Chat', 'Analysis'],
    freeAlternative: { name: 'ChatGPT', url: 'https://chat.openai.com' },
  },
  {
    id: '8',
    name: 'Perplexity AI',
    description: 'AI-powered search engine that provides direct answers with citations.',
    websiteUrl: 'https://www.perplexity.ai',
    imageUrl: 'https://picsum.photos/seed/perplexity/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'Research', 'AI'],
    freeAlternative: { name: 'Brave Search', url: 'https://brave.com/search' },
  },
  {
    id: '9',
    name: 'Descript',
    description: 'Simple, powerful, and fun way to edit videos and podcasts.',
    websiteUrl: 'https://www.descript.com',
    imageUrl: 'https://picsum.photos/seed/descript/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Editing', 'Podcast', 'Audio'],
    freeAlternative: { name: 'Adobe Podcast', url: 'https://podcast.adobe.com' },
  },
  {
    id: '10',
    name: 'Cursor',
    description: 'The AI Code Editor. Built for pair programming with AI.',
    websiteUrl: 'https://cursor.sh',
    imageUrl: 'https://picsum.photos/seed/cursor/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['IDE', 'Coding', 'AI'],
    freeAlternative: { name: 'VS Code', url: 'https://code.visualstudio.com' },
  },
  {
    id: '11',
    name: 'Suno',
    description: 'Create high-quality music and songs with AI in any style.',
    websiteUrl: 'https://suno.com',
    imageUrl: 'https://picsum.photos/seed/suno/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Music', 'Audio', 'AI'],
    freeAlternative: { name: 'Udio', url: 'https://udio.com' },
  },
  {
    id: '12',
    name: 'Canva Magic Studio',
    description: 'AI-powered design tools to help you create stunning visuals effortlessly.',
    websiteUrl: 'https://www.canva.com/magic-studio',
    imageUrl: 'https://picsum.photos/seed/canva/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'Graphics', 'AI', 'Cards', 'Posters', 'Social Media', 'Templates', 'YouTube Thumbnail', 'Thumbnail'],
    freeAlternative: { name: 'Microsoft Designer', url: 'https://designer.microsoft.com' },
  },
  {
    id: '13',
    name: 'Grammarly',
    description: 'AI writing assistant that helps you write clearly and effectively.',
    websiteUrl: 'https://www.grammarly.com',
    imageUrl: 'https://picsum.photos/seed/grammarly/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Editing', 'AI'],
    freeAlternative: { name: 'LanguageTool', url: 'https://languagetool.org' },
  },
  {
    id: '14',
    name: 'Notion AI',
    description: 'AI-powered workspace that helps you write, plan, and organize.',
    websiteUrl: 'https://www.notion.so/product/ai',
    imageUrl: 'https://picsum.photos/seed/notion/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Notes', 'Planning', 'AI'],
    freeAlternative: { name: 'Obsidian', url: 'https://obsidian.md' },
  },
  {
    id: '15',
    name: 'Runway Gen-3 Alpha',
    description: 'Advanced AI video generation model for high-fidelity creative control.',
    websiteUrl: 'https://runwayml.com',
    imageUrl: 'https://picsum.photos/seed/runway/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'Art', 'AI'],
    freeAlternative: { name: 'Stable Video Diffusion', url: 'https://stability.ai' },
  },
  {
    id: '16',
    name: 'Leonardo.ai',
    description: 'Create production-quality visual assets for your projects with AI.',
    websiteUrl: 'https://leonardo.ai',
    imageUrl: 'https://picsum.photos/seed/leonardo/400/200',
    category: 'Image Generation',
    pricingModel: 'Freemium',
    tags: ['Art', 'Images', 'AI', 'YouTube Thumbnail', 'Thumbnail'],
    freeAlternative: { name: 'Stable Diffusion', url: 'https://stability.ai' },
  },
  {
    id: '17',
    name: 'Gamma',
    description: 'A new medium for presenting ideas, powered by AI.',
    websiteUrl: 'https://gamma.app',
    imageUrl: 'https://picsum.photos/seed/gamma/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Presentations', 'Design', 'AI'],
    freeAlternative: { name: 'Google Slides', url: 'https://slides.google.com' },
  },
  {
    id: '18',
    name: 'Poe',
    description: 'Fast, helpful AI chat interface for multiple models.',
    websiteUrl: 'https://poe.com',
    imageUrl: 'https://picsum.photos/seed/poe/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['Chat', 'AI', 'Models'],
    freeAlternative: { name: 'HuggingChat', url: 'https://huggingface.co/chat' },
  },
  {
    id: '19',
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation for high-quality visuals.',
    websiteUrl: 'https://stability.ai',
    imageUrl: 'https://picsum.photos/seed/stablediffusion/400/200',
    category: 'Image Generation',
    pricingModel: 'Free',
    tags: ['Art', 'Open Source', 'AI', 'YouTube Thumbnail', 'Thumbnail'],
  },
  {
    id: '20',
    name: 'Otter.ai',
    description: 'AI meeting assistant that records audio, writes notes, and captures slides.',
    websiteUrl: 'https://otter.ai',
    imageUrl: 'https://picsum.photos/seed/otter/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Transcription', 'Meetings', 'AI'],
    freeAlternative: { name: 'Microsoft Teams', url: 'https://www.microsoft.com/teams' },
  },
  {
    id: '21',
    name: 'Gemini',
    description: "Google's most capable AI model, built to be multimodal from the ground up.",
    websiteUrl: 'https://gemini.google.com',
    imageUrl: 'https://picsum.photos/seed/gemini/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Google', 'Multimodal'],
    freeAlternative: { name: 'ChatGPT', url: 'https://chat.openai.com' },
  },
  {
    id: '22',
    name: 'DALL-E 3',
    description: 'OpenAI\'s latest image generation system that understands significantly more nuance.',
    websiteUrl: 'https://openai.com/dall-e-3',
    imageUrl: 'https://picsum.photos/seed/dalle/400/200',
    category: 'Image Generation',
    pricingModel: 'Paid',
    tags: ['Art', 'Images', 'OpenAI', 'YouTube Thumbnail', 'Thumbnail'],
    freeAlternative: { name: 'Bing Image Creator', url: 'https://www.bing.com/images/create' },
  },
  {
    id: '23',
    name: 'Adobe Firefly',
    description: 'Generative AI made for creators, integrated directly into Adobe Creative Cloud.',
    websiteUrl: 'https://www.adobe.com/firefly',
    imageUrl: 'https://picsum.photos/seed/firefly/400/200',
    category: 'Image Generation',
    pricingModel: 'Freemium',
    tags: ['Design', 'Adobe', 'Images', 'YouTube Thumbnail', 'Thumbnail'],
    freeAlternative: { name: 'Leonardo.ai', url: 'https://leonardo.ai' },
  },
  {
    id: '24',
    name: 'Replit Ghostwriter',
    description: 'AI-powered coding assistant integrated directly into the Replit IDE.',
    websiteUrl: 'https://replit.com/ai',
    imageUrl: 'https://picsum.photos/seed/replit/400/200',
    category: 'Coding',
    pricingModel: 'Paid',
    tags: ['Coding', 'IDE', 'Development'],
    freeAlternative: { name: 'Codeium', url: 'https://codeium.com' },
  },
  {
    id: '25',
    name: 'Copy.ai',
    description: 'AI platform for generating high-quality marketing copy and content.',
    websiteUrl: 'https://www.copy.ai',
    imageUrl: 'https://picsum.photos/seed/copyai/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Marketing', 'Writing', 'Business'],
    freeAlternative: { name: 'Writesonic', url: 'https://writesonic.com' },
  },
  {
    id: '26',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model that can create realistic and imaginative scenes.',
    websiteUrl: 'https://openai.com/sora',
    imageUrl: 'https://picsum.photos/seed/sora/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'OpenAI', 'Realistic'],
    freeAlternative: { name: 'Luma Dream Machine', url: 'https://lumalabs.ai/dream-machine' },
  },
  {
    id: '27',
    name: 'HeyGen',
    description: 'Create professional AI videos with talking avatars in minutes.',
    websiteUrl: 'https://www.heygen.com',
    imageUrl: 'https://picsum.photos/seed/heygen/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Avatars', 'Marketing'],
    freeAlternative: { name: 'D-ID', url: 'https://www.d-id.com' },
  },
  {
    id: '28',
    name: 'Adobe Podcast',
    description: 'AI-powered audio recording and editing, all in the web browser.',
    websiteUrl: 'https://podcast.adobe.com',
    imageUrl: 'https://picsum.photos/seed/adobepodcast/400/200',
    category: 'Audio',
    pricingModel: 'Free',
    tags: ['Audio', 'Podcast', 'Editing'],
  },
  {
    id: '29',
    name: 'You.com',
    description: 'The AI search engine that gives you control over your search experience.',
    websiteUrl: 'https://you.com',
    imageUrl: 'https://picsum.photos/seed/youcom/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'AI', 'Privacy'],
    freeAlternative: { name: 'Brave Search', url: 'https://brave.com/search' },
  },
  {
    id: '30',
    name: 'Microsoft Copilot',
    description: 'Your everyday AI companion, integrated across Microsoft 365 and Windows.',
    websiteUrl: 'https://copilot.microsoft.com',
    imageUrl: 'https://picsum.photos/seed/mscopilot/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Productivity', 'Microsoft', 'Business'],
    freeAlternative: { name: 'Gemini', url: 'https://gemini.google.com' },
  },
  {
    id: '31',
    name: 'Brave Search',
    description: 'Privacy-focused search engine with AI-powered summaries and answers.',
    websiteUrl: 'https://brave.com/search',
    imageUrl: 'https://picsum.photos/seed/brave/400/200',
    category: 'Search',
    pricingModel: 'Free',
    tags: ['Search', 'Privacy', 'AI'],
  },
  {
    id: '32',
    name: 'Phind',
    description: 'The AI search engine for developers. Get answers to technical questions instantly.',
    websiteUrl: 'https://www.phind.com',
    imageUrl: 'https://picsum.photos/seed/phind/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'Coding', 'Technical'],
    freeAlternative: { name: 'Perplexity AI', url: 'https://www.perplexity.ai' },
  },
  {
    id: '33',
    name: 'Figma AI',
    description: 'AI-powered design features to help you design faster and better in Figma.',
    websiteUrl: 'https://www.figma.com/ai',
    imageUrl: 'https://picsum.photos/seed/figma/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'UI/UX', 'Figma'],
    freeAlternative: { name: 'Penpot', url: 'https://penpot.app' },
  },
  {
    id: '34',
    name: 'Microsoft Designer',
    description: 'Create stunning designs and images in a flash with AI.',
    websiteUrl: 'https://designer.microsoft.com',
    imageUrl: 'https://picsum.photos/seed/msdesigner/400/200',
    category: 'Design',
    pricingModel: 'Free',
    tags: ['Design', 'Graphics', 'Microsoft', 'Cards', 'Posters', 'Social Media', 'AI', 'YouTube Thumbnail', 'Thumbnail'],
  },
  {
    id: '35',
    name: 'Tabnine',
    description: 'AI assistant for software developers. Code faster with AI-powered completions.',
    websiteUrl: 'https://www.tabnine.com',
    imageUrl: 'https://picsum.photos/seed/tabnine/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['Coding', 'Autocomplete', 'AI'],
    freeAlternative: { name: 'Codeium', url: 'https://codeium.com' },
  },
  {
    id: '36',
    name: 'Writesonic',
    description: 'AI writing tool for creating SEO-friendly content for blogs, ads, and more.',
    websiteUrl: 'https://writesonic.com',
    imageUrl: 'https://picsum.photos/seed/writesonic/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'SEO', 'Marketing'],
    freeAlternative: { name: 'Copy.ai', url: 'https://www.copy.ai' },
  },
  {
    id: '37',
    name: 'Grok',
    description: 'AI assistant from xAI with real-time access to information via X.',
    websiteUrl: 'https://x.ai',
    imageUrl: 'https://picsum.photos/seed/grok/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['AI', 'Chat', 'Real-time'],
    freeAlternative: { name: 'ChatGPT', url: 'https://chat.openai.com' },
  },
  {
    id: '38',
    name: 'Mistral AI',
    description: 'Open-weight AI models that are efficient and powerful.',
    websiteUrl: 'https://mistral.ai',
    imageUrl: 'https://picsum.photos/seed/mistral/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Open Source', 'Models'],
  },
  {
    id: '39',
    name: 'Hugging Face',
    description: 'The platform where the machine learning community builds the future.',
    websiteUrl: 'https://huggingface.co',
    imageUrl: 'https://picsum.photos/seed/huggingface/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['AI', 'Models', 'Development'],
  },
  {
    id: '40',
    name: 'Character.ai',
    description: 'Chat with AI personalities or create your own characters.',
    websiteUrl: 'https://character.ai',
    imageUrl: 'https://picsum.photos/seed/characterai/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['Chat', 'Fun', 'Personalities'],
  },
  {
    id: '41',
    name: 'Synthesia',
    description: 'Create professional AI videos with human-like avatars from text.',
    websiteUrl: 'https://www.synthesia.io',
    imageUrl: 'https://picsum.photos/seed/synthesia/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'Avatars', 'Business'],
    freeAlternative: { name: 'HeyGen', url: 'https://www.heygen.com' },
  },
  {
    id: '42',
    name: 'DeepL',
    description: 'The world\'s most accurate AI translator for text and documents.',
    websiteUrl: 'https://www.deepl.com',
    imageUrl: 'https://picsum.photos/seed/deepl/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Translation', 'Language', 'AI'],
    freeAlternative: { name: 'Google Translate', url: 'https://translate.google.com' },
  },
  {
    id: '43',
    name: 'Quillbot',
    description: 'AI-powered paraphrasing tool that helps you rewrite and improve your text.',
    websiteUrl: 'https://quillbot.com',
    imageUrl: 'https://picsum.photos/seed/quillbot/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Editing', 'Paraphrasing'],
    freeAlternative: { name: 'Wordtune', url: 'https://www.wordtune.com' },
  },
  {
    id: '44',
    name: 'Fireflies.ai',
    description: 'AI meeting assistant that automatically records and transcribes meetings.',
    websiteUrl: 'https://fireflies.ai',
    imageUrl: 'https://picsum.photos/seed/fireflies/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Meetings', 'Transcription', 'Notes'],
    freeAlternative: { name: 'Otter.ai', url: 'https://otter.ai' },
  },
  {
    id: '45',
    name: 'Codeium',
    description: 'Free AI-powered code completion and search for developers.',
    websiteUrl: 'https://codeium.com',
    imageUrl: 'https://picsum.photos/seed/codeium/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['Coding', 'Autocomplete', 'Free'],
    freeAlternative: { name: 'GitHub Copilot', url: 'https://github.com/features/copilot' },
  },
  {
    id: '46',
    name: 'Udio',
    description: 'AI music generation that creates full songs with vocals and instruments.',
    websiteUrl: 'https://udio.com',
    imageUrl: 'https://picsum.photos/seed/udio/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Music', 'Audio', 'AI'],
    freeAlternative: { name: 'Suno', url: 'https://suno.com' },
  },
  {
    id: '47',
    name: 'Kling AI',
    description: 'Advanced AI video generation for cinematic and realistic results.',
    websiteUrl: 'https://klingai.com',
    imageUrl: 'https://picsum.photos/seed/kling/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Cinema', 'AI'],
    freeAlternative: { name: 'Luma Dream Machine', url: 'https://lumalabs.ai/dream-machine' },
  },
  {
    id: '48',
    name: 'Pi',
    description: 'A personal AI assistant designed to be supportive and conversational.',
    websiteUrl: 'https://pi.ai',
    imageUrl: 'https://picsum.photos/seed/piai/400/200',
    category: 'Chatbot',
    pricingModel: 'Free',
    tags: ['AI', 'Chat', 'Personal'],
  },
  {
    id: '49',
    name: 'Veed.io',
    description: 'Online video editor with AI tools for subtitles, voiceovers, and more.',
    websiteUrl: 'https://www.veed.io',
    imageUrl: 'https://picsum.photos/seed/veedio/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Editing', 'Subtitles'],
    freeAlternative: { name: 'CapCut', url: 'https://www.capcut.com' },
  },
  {
    id: '50',
    name: 'CapCut',
    description: 'All-in-one video editor with AI features for social media creators.',
    websiteUrl: 'https://www.capcut.com',
    imageUrl: 'https://picsum.photos/seed/capcut/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Editing', 'Social Media'],
    freeAlternative: { name: 'Veed.io', url: 'https://www.veed.io' },
  },
  {
    id: '51',
    name: 'Scribe',
    description: 'AI tool that automatically creates step-by-step guides for any process.',
    websiteUrl: 'https://scribehow.com',
    imageUrl: 'https://picsum.photos/seed/scribe/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Guides', 'Documentation', 'AI'],
  },
  {
    id: '52',
    name: 'Beautiful.ai',
    description: 'AI presentation software that designs your slides for you.',
    websiteUrl: 'https://www.beautiful.ai',
    imageUrl: 'https://picsum.photos/seed/beautifulai/400/200',
    category: 'Design',
    pricingModel: 'Paid',
    tags: ['Presentations', 'Design', 'AI'],
    freeAlternative: { name: 'Gamma', url: 'https://gamma.app' },
  },
  {
    id: '53',
    name: 'Rytr',
    description: 'AI writing assistant that helps you create high-quality content in seconds.',
    websiteUrl: 'https://rytr.me',
    imageUrl: 'https://picsum.photos/seed/rytr/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Content', 'AI'],
    freeAlternative: { name: 'Writesonic', url: 'https://writesonic.com' },
  },
  {
    id: '54',
    name: 'Wordtune',
    description: 'AI writing companion that helps you rephrase and refine your sentences.',
    websiteUrl: 'https://www.wordtune.com',
    imageUrl: 'https://picsum.photos/seed/wordtune/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Editing', 'AI'],
    freeAlternative: { name: 'Quillbot', url: 'https://quillbot.com' },
  },
  {
    id: '55',
    name: 'Surfer SEO',
    description: 'AI-powered SEO tool that helps you optimize your content for search engines.',
    websiteUrl: 'https://surferseo.com',
    imageUrl: 'https://picsum.photos/seed/surferseo/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Marketing', 'Writing'],
    freeAlternative: { name: 'NeuralText', url: 'https://www.neuraltext.com' },
  },
  {
    id: '56',
    name: 'NeuralText',
    description: 'AI writing and SEO tool that helps you automate your content workflow.',
    websiteUrl: 'https://www.neuraltext.com',
    imageUrl: 'https://picsum.photos/seed/neuraltext/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['SEO', 'Writing', 'AI'],
    freeAlternative: { name: 'Surfer SEO', url: 'https://surferseo.com' },
  },
  {
    id: '57',
    name: 'InVideo',
    description: 'AI video creation platform that helps you turn text into professional videos.',
    websiteUrl: 'https://invideo.io',
    imageUrl: 'https://picsum.photos/seed/invideo/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Marketing', 'AI'],
    freeAlternative: { name: 'Pictory', url: 'https://pictory.ai' },
  },
  {
    id: '58',
    name: 'Pictory',
    description: 'AI tool that automatically creates short, highly-sharable branded videos.',
    websiteUrl: 'https://pictory.ai',
    imageUrl: 'https://picsum.photos/seed/pictory/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Social Media', 'AI'],
    freeAlternative: { name: 'InVideo', url: 'https://invideo.io' },
  },
  {
    id: '59',
    name: 'OpusClip',
    description: 'AI tool that turns long videos into viral short clips with one click.',
    websiteUrl: 'https://www.opus.pro',
    imageUrl: 'https://picsum.photos/seed/opusclip/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Shorts', 'AI'],
    freeAlternative: { name: 'Munch', url: 'https://www.getmunch.com' },
  },
  {
    id: '60',
    name: 'Munch',
    description: 'AI platform for extracting the most engaging clips from long-form videos.',
    websiteUrl: 'https://www.getmunch.com',
    imageUrl: 'https://picsum.photos/seed/munch/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Marketing', 'AI'],
    freeAlternative: { name: 'OpusClip', url: 'https://www.opus.pro' },
  },
  {
    id: '61',
    name: 'Vidyo.ai',
    description: 'AI tool for creating short social media clips from long-form content.',
    websiteUrl: 'https://vidyo.ai',
    imageUrl: 'https://picsum.photos/seed/vidyo/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Social Media', 'AI'],
    freeAlternative: { name: 'Dumme', url: 'https://dumme.com' },
  },
  {
    id: '62',
    name: 'Dumme',
    description: 'AI tool that automatically finds and clips the best moments from your videos.',
    websiteUrl: 'https://dumme.com',
    imageUrl: 'https://picsum.photos/seed/dumme/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Shorts', 'AI'],
    freeAlternative: { name: 'Vidyo.ai', url: 'https://vidyo.ai' },
  },
  {
    id: '63',
    name: 'Submagic',
    description: 'AI tool for generating dynamic captions and subtitles for short videos.',
    websiteUrl: 'https://www.submagic.co',
    imageUrl: 'https://picsum.photos/seed/submagic/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'Captions', 'AI'],
    freeAlternative: { name: 'Captions.ai', url: 'https://www.captions.ai' },
  },
  {
    id: '64',
    name: 'Captions.ai',
    description: 'AI-powered camera and editing app for creators to make talking videos.',
    websiteUrl: 'https://www.captions.ai',
    imageUrl: 'https://picsum.photos/seed/captions/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Editing', 'AI'],
    freeAlternative: { name: 'Submagic', url: 'https://www.submagic.co' },
  },
  {
    id: '65',
    name: 'Lovo.ai',
    description: 'AI voice generator and text-to-speech platform for creators and businesses.',
    websiteUrl: 'https://lovo.ai',
    imageUrl: 'https://picsum.photos/seed/lovo/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Voice', 'Audio', 'TTS'],
    freeAlternative: { name: 'ElevenLabs', url: 'https://elevenlabs.io' },
  },
  {
    id: '66',
    name: 'Murf AI',
    description: 'AI voice generator that turns text into high-quality human-like speech.',
    websiteUrl: 'https://murf.ai',
    imageUrl: 'https://picsum.photos/seed/murf/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Voice', 'Audio', 'TTS'],
    freeAlternative: { name: 'ElevenLabs', url: 'https://elevenlabs.io' },
  },
  {
    id: '67',
    name: 'Speechify',
    description: 'AI reading assistant that turns any text into high-quality audio.',
    websiteUrl: 'https://speechify.com',
    imageUrl: 'https://picsum.photos/seed/speechify/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Audio', 'TTS', 'Reading'],
    freeAlternative: { name: 'NaturalReader', url: 'https://www.naturalreaders.com' },
  },
  {
    id: '68',
    name: 'NaturalReader',
    description: 'AI text-to-speech tool for personal, commercial, and educational use.',
    websiteUrl: 'https://www.naturalreaders.com',
    imageUrl: 'https://picsum.photos/seed/naturalreader/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Audio', 'TTS', 'Education'],
    freeAlternative: { name: 'Speechify', url: 'https://speechify.com' },
  },
  {
    id: '69',
    name: 'Uizard',
    description: 'AI-powered design tool for creating wireframes, mockups, and prototypes.',
    websiteUrl: 'https://uizard.io',
    imageUrl: 'https://picsum.photos/seed/uizard/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'UI/UX', 'AI'],
    freeAlternative: { name: 'Figma', url: 'https://www.figma.com' },
  },
  {
    id: '70',
    name: 'Frammer',
    description: 'AI-powered website builder that helps you design and publish sites fast.',
    websiteUrl: 'https://www.framer.com',
    imageUrl: 'https://picsum.photos/seed/framer/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'Web', 'AI'],
    freeAlternative: { name: 'Webflow', url: 'https://webflow.com' },
  },
  {
    id: '71',
    name: 'Webflow',
    description: 'Professional website builder with AI features for design and development.',
    websiteUrl: 'https://webflow.com',
    imageUrl: 'https://picsum.photos/seed/webflow/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Web', 'Design', 'Development'],
    freeAlternative: { name: 'Framer', url: 'https://www.framer.com' },
  },
  {
    id: '72',
    name: 'Dora AI',
    description: 'AI-powered tool for creating stunning 3D websites with ease.',
    websiteUrl: 'https://www.dora.run',
    imageUrl: 'https://picsum.photos/seed/dora/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Web', '3D', 'AI'],
  },
  {
    id: '73',
    name: 'Spline AI',
    description: 'AI-powered 3D design tool for creating interactive 3D experiences.',
    websiteUrl: 'https://spline.design/ai',
    imageUrl: 'https://picsum.photos/seed/spline/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['3D', 'Design', 'AI'],
  },
  {
    id: '74',
    name: 'Luma AI',
    description: 'AI tool for creating realistic 3D models and scenes from photos.',
    websiteUrl: 'https://lumalabs.ai',
    imageUrl: 'https://picsum.photos/seed/luma3d/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['3D', 'Modeling', 'AI'],
  },
  {
    id: '75',
    name: 'Meshy',
    description: 'AI-powered 3D generative tool for creating 3D assets from text and images.',
    websiteUrl: 'https://www.meshy.ai',
    imageUrl: 'https://picsum.photos/seed/meshy/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['3D', 'Assets', 'AI'],
  },
  {
    id: '76',
    name: 'Polycam',
    description: 'AI-powered 3D scanning app for creating 3D models with your phone.',
    websiteUrl: 'https://poly.cam',
    imageUrl: 'https://picsum.photos/seed/polycam/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['3D', 'Scanning', 'AI'],
  },
  {
    id: '77',
    name: 'Rose.ai',
    description: 'AI-powered data platform that helps you find, visualize, and share data.',
    websiteUrl: 'https://rose.ai',
    imageUrl: 'https://picsum.photos/seed/rose/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Data', 'Analysis', 'AI'],
  },
  {
    id: '78',
    name: 'Julius AI',
    description: 'AI data analyst that helps you analyze and visualize your data.',
    websiteUrl: 'https://julius.ai',
    imageUrl: 'https://picsum.photos/seed/julius/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Data', 'Analysis', 'AI'],
  },
  {
    id: '79',
    name: 'Akkio',
    description: 'AI platform for building and deploying predictive models without code.',
    websiteUrl: 'https://www.akkio.com',
    imageUrl: 'https://picsum.photos/seed/akkio/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Data', 'Prediction', 'AI'],
  },
  {
    id: '80',
    name: 'MonkeyLearn',
    description: 'AI platform for text analysis and data visualization.',
    websiteUrl: 'https://monkeylearn.com',
    imageUrl: 'https://picsum.photos/seed/monkeylearn/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Data', 'Text Analysis', 'AI'],
  },
  {
    id: '81',
    name: 'Levity',
    description: 'AI platform for automating repetitive tasks with machine learning.',
    websiteUrl: 'https://levity.ai',
    imageUrl: 'https://picsum.photos/seed/levity/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Automation', 'Tasks', 'AI'],
  },
  {
    id: '82',
    name: 'Zapier Central',
    description: 'AI-powered automation platform that helps you build custom AI agents.',
    websiteUrl: 'https://zapier.com/central',
    imageUrl: 'https://picsum.photos/seed/zapier/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Automation', 'Agents', 'AI'],
  },
  {
    id: '83',
    name: 'Make.com',
    description: 'Visual automation platform with AI features for building complex workflows.',
    websiteUrl: 'https://www.make.com',
    imageUrl: 'https://picsum.photos/seed/make/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Automation', 'Workflows', 'AI'],
  },
  {
    id: '84',
    name: 'Bardeen',
    description: 'AI-powered automation tool that helps you automate your browser tasks.',
    websiteUrl: 'https://www.bardeen.ai',
    imageUrl: 'https://picsum.photos/seed/bardeen/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Automation', 'Browser', 'AI'],
  },
  {
    id: '85',
    name: 'Lindy.ai',
    description: 'AI personal assistant that can handle your calendar, emails, and more.',
    websiteUrl: 'https://www.lindy.ai',
    imageUrl: 'https://picsum.photos/seed/lindy/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Assistant', 'Productivity', 'AI'],
  },
  {
    id: '86',
    name: 'HyperWrite',
    description: 'AI writing assistant that helps you write faster and better everywhere.',
    websiteUrl: 'https://www.hyperwriteai.com',
    imageUrl: 'https://picsum.photos/seed/hyperwrite/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Assistant', 'AI'],
  },
  {
    id: '87',
    name: 'Anyword',
    description: 'AI copywriting platform that helps you create high-performing marketing copy.',
    websiteUrl: 'https://anyword.com',
    imageUrl: 'https://picsum.photos/seed/anyword/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Marketing', 'Writing', 'AI'],
  },
  {
    id: '88',
    name: 'Peppertype.ai',
    description: 'AI content creation tool that helps you generate high-quality content fast.',
    websiteUrl: 'https://www.peppercontent.io/peppertype-ai',
    imageUrl: 'https://picsum.photos/seed/peppertype/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Content', 'Writing', 'AI'],
  },
  {
    id: '89',
    name: 'Frase.io',
    description: 'AI-powered content optimization tool that helps you rank higher on search engines.',
    websiteUrl: 'https://www.frase.io',
    imageUrl: 'https://picsum.photos/seed/frase/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Content', 'AI'],
  },
  {
    id: '90',
    name: 'MarketMuse',
    description: 'AI-powered content research and optimization platform for SEO teams.',
    websiteUrl: 'https://www.marketmuse.com',
    imageUrl: 'https://picsum.photos/seed/marketmuse/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Research', 'AI'],
  },
  {
    id: '91',
    name: 'Scalenut',
    description: 'AI-powered content marketing platform for SEO and content creation.',
    websiteUrl: 'https://www.scalenut.com',
    imageUrl: 'https://picsum.photos/seed/scalenut/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Marketing', 'AI'],
  },
  {
    id: '92',
    name: 'ContentBot',
    description: 'AI writing assistant for founders, marketers, and content creators.',
    websiteUrl: 'https://contentbot.ai',
    imageUrl: 'https://picsum.photos/seed/contentbot/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Marketing', 'AI'],
  },
  {
    id: '93',
    name: 'Outranking',
    description: 'AI-powered SEO content strategy and writing platform.',
    websiteUrl: 'https://www.outranking.io',
    imageUrl: 'https://picsum.photos/seed/outranking/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Strategy', 'AI'],
  },
  {
    id: '94',
    name: 'GrowthBar',
    description: 'AI-powered SEO tool for content creators and marketing teams.',
    websiteUrl: 'https://www.growthbarseo.com',
    imageUrl: 'https://picsum.photos/seed/growthbar/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['SEO', 'Marketing', 'AI'],
  },
  {
    id: '95',
    name: 'Ink for All',
    description: 'AI-powered content marketing platform for SEO and writing.',
    websiteUrl: 'https://inkforall.com',
    imageUrl: 'https://picsum.photos/seed/inkforall/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['SEO', 'Writing', 'AI'],
  },
  {
    id: '96',
    name: 'Textio',
    description: 'AI-powered writing assistant for inclusive and effective communication.',
    websiteUrl: 'https://textio.com',
    imageUrl: 'https://picsum.photos/seed/textio/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Writing', 'Inclusion', 'AI'],
  },
  {
    id: '97',
    name: 'Lavender',
    description: 'AI email assistant that helps you write better emails faster.',
    websiteUrl: 'https://www.lavender.ai',
    imageUrl: 'https://picsum.photos/seed/lavender/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Email', 'Writing', 'AI'],
  },
  {
    id: '98',
    name: 'Regie.ai',
    description: 'AI platform for sales teams to automate content and outreach.',
    websiteUrl: 'https://www.regie.ai',
    imageUrl: 'https://picsum.photos/seed/regie/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Sales', 'Content', 'AI'],
  },
  {
    id: '99',
    name: 'Gong.io',
    description: 'AI platform for revenue teams to analyze customer interactions.',
    websiteUrl: 'https://www.gong.io',
    imageUrl: 'https://picsum.photos/seed/gong/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Analysis', 'AI'],
  },
  {
    id: '100',
    name: 'Chorus.ai',
    description: 'AI-powered conversation intelligence platform for sales teams.',
    websiteUrl: 'https://www.chorus.ai',
    imageUrl: 'https://picsum.photos/seed/chorus/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Intelligence', 'AI'],
  },
  {
    id: '101',
    name: 'Salesloft',
    description: 'AI-powered sales engagement platform for revenue teams.',
    websiteUrl: 'https://salesloft.com',
    imageUrl: 'https://picsum.photos/seed/salesloft/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Engagement', 'AI'],
  },
  {
    id: '102',
    name: 'Outreach',
    description: 'AI-powered sales execution platform for revenue teams.',
    websiteUrl: 'https://www.outreach.io',
    imageUrl: 'https://picsum.photos/seed/outreach/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Execution', 'AI'],
  },
  {
    id: '103',
    name: 'Apollo.io',
    description: 'AI-powered sales intelligence and engagement platform.',
    websiteUrl: 'https://www.apollo.io',
    imageUrl: 'https://picsum.photos/seed/apollo/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Sales', 'Intelligence', 'AI'],
  },
  {
    id: '104',
    name: 'ZoomInfo',
    description: 'AI-powered go-to-market platform for sales and marketing teams.',
    websiteUrl: 'https://www.zoominfo.com',
    imageUrl: 'https://picsum.photos/seed/zoominfo/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Marketing', 'AI'],
  },
  {
    id: '105',
    name: 'Clearbit',
    description: 'AI-powered data enrichment platform for sales and marketing teams.',
    websiteUrl: 'https://clearbit.com',
    imageUrl: 'https://picsum.photos/seed/clearbit/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Data', 'Marketing', 'AI'],
  },
  {
    id: '106',
    name: '6sense',
    description: 'AI-powered account-based marketing platform for revenue teams.',
    websiteUrl: 'https://6sense.com',
    imageUrl: 'https://picsum.photos/seed/6sense/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Marketing', 'ABM', 'AI'],
  },
  {
    id: '107',
    name: 'Demandbase',
    description: 'AI-powered account-based marketing platform for B2B teams.',
    websiteUrl: 'https://www.demandbase.com',
    imageUrl: 'https://picsum.photos/seed/demandbase/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Marketing', 'ABM', 'AI'],
  },
  {
    id: '108',
    name: 'Mutiny',
    description: 'AI-powered website personalization platform for marketing teams.',
    websiteUrl: 'https://www.mutinyhq.com',
    imageUrl: 'https://picsum.photos/seed/mutiny/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Marketing', 'Personalization', 'AI'],
  },
  {
    id: '109',
    name: 'Drift',
    description: 'AI-powered conversational marketing and sales platform.',
    websiteUrl: 'https://www.drift.com',
    imageUrl: 'https://picsum.photos/seed/drift/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Marketing', 'Sales', 'AI'],
  },
  {
    id: '110',
    name: 'Intercom Fin',
    description: 'AI-powered customer service bot that provides instant answers.',
    websiteUrl: 'https://www.intercom.com/fin',
    imageUrl: 'https://picsum.photos/seed/intercom/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '111',
    name: 'Ada',
    description: 'AI-powered customer service platform for automated support.',
    websiteUrl: 'https://www.ada.support',
    imageUrl: 'https://picsum.photos/seed/ada/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '112',
    name: 'Forethought',
    description: 'AI-powered customer service platform for automated support and intelligence.',
    websiteUrl: 'https://www.forethought.ai',
    imageUrl: 'https://picsum.photos/seed/forethought/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '113',
    name: 'Solvvy',
    description: 'AI-powered customer service platform for automated support and self-service.',
    websiteUrl: 'https://solvvy.com',
    imageUrl: 'https://picsum.photos/seed/solvvy/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '114',
    name: 'Netomi',
    description: 'AI-powered customer service platform for automated support across channels.',
    websiteUrl: 'https://www.netomi.com',
    imageUrl: 'https://picsum.photos/seed/netomi/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '115',
    name: 'Ultimate.ai',
    description: 'AI-powered customer service platform for automated support in any language.',
    websiteUrl: 'https://www.ultimate.ai',
    imageUrl: 'https://picsum.photos/seed/ultimate/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '116',
    name: 'Kustomer IQ',
    description: 'AI-powered customer service platform for automated support and intelligence.',
    websiteUrl: 'https://www.kustomer.com/product/iq',
    imageUrl: 'https://picsum.photos/seed/kustomer/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '117',
    name: 'Zendesk Answer Bot',
    description: 'AI-powered customer service bot that provides instant answers to customers.',
    websiteUrl: 'https://www.zendesk.com/service/answer-bot',
    imageUrl: 'https://picsum.photos/seed/zendesk/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '118',
    name: 'Salesforce Einstein',
    description: 'AI-powered intelligence platform integrated across Salesforce products.',
    websiteUrl: 'https://www.salesforce.com/products/einstein',
    imageUrl: 'https://picsum.photos/seed/salesforce/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['CRM', 'Intelligence', 'AI'],
  },
  {
    id: '119',
    name: 'HubSpot AI',
    description: 'AI-powered tools integrated across HubSpot products for marketing, sales, and service.',
    websiteUrl: 'https://www.hubspot.com/products/ai',
    imageUrl: 'https://picsum.photos/seed/hubspot/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['CRM', 'Marketing', 'AI'],
  },
  {
    id: '120',
    name: 'Zoho Zia',
    description: 'AI-powered assistant integrated across Zoho products for business intelligence.',
    websiteUrl: 'https://www.zoho.com/zia',
    imageUrl: 'https://picsum.photos/seed/zoho/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Business', 'Intelligence', 'AI'],
  },
  {
    id: '121',
    name: 'Freshworks Freddy',
    description: 'AI-powered assistant integrated across Freshworks products for customer engagement.',
    websiteUrl: 'https://www.freshworks.com/freddy-ai',
    imageUrl: 'https://picsum.photos/seed/freshworks/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Service', 'Engagement', 'AI'],
  },
  {
    id: '122',
    name: 'Pipedrive AI',
    description: 'AI-powered sales assistant integrated across Pipedrive products for sales teams.',
    websiteUrl: 'https://www.pipedrive.com/en/features/ai-sales-assistant',
    imageUrl: 'https://picsum.photos/seed/pipedrive/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Assistant', 'AI'],
  },
  {
    id: '123',
    name: 'Avoma',
    description: 'AI-powered meeting assistant for revenue teams to capture and analyze meetings.',
    websiteUrl: 'https://www.avoma.com',
    imageUrl: 'https://picsum.photos/seed/avoma/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Meetings', 'Analysis', 'AI'],
  },
  {
    id: '124',
    name: 'Wingman',
    description: 'AI-powered sales intelligence platform for revenue teams to analyze calls.',
    websiteUrl: 'https://www.trywingman.com',
    imageUrl: 'https://picsum.photos/seed/wingman/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Intelligence', 'AI'],
  },
  {
    id: '125',
    name: 'Jiminny',
    description: 'AI-powered conversation intelligence platform for sales and customer success teams.',
    websiteUrl: 'https://www.jiminny.com',
    imageUrl: 'https://picsum.photos/seed/jiminny/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Intelligence', 'AI'],
  },
  {
    id: '126',
    name: 'Refract',
    description: 'AI-powered sales coaching and intelligence platform for revenue teams.',
    websiteUrl: 'https://www.refract.ai',
    imageUrl: 'https://picsum.photos/seed/refract/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Coaching', 'AI'],
  },
  {
    id: '127',
    name: 'ExecVision',
    description: 'AI-powered conversation intelligence platform for sales and service teams.',
    websiteUrl: 'https://www.execvision.ai',
    imageUrl: 'https://picsum.photos/seed/execvision/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Sales', 'Intelligence', 'AI'],
  },
  {
    id: '128',
    name: 'Balto',
    description: 'AI-powered real-time guidance for contact center agents.',
    websiteUrl: 'https://www.balto.ai',
    imageUrl: 'https://picsum.photos/seed/balto/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Guidance', 'AI'],
  },
  {
    id: '129',
    name: 'Cogito',
    description: 'AI-powered real-time emotional intelligence for contact center agents.',
    websiteUrl: 'https://www.cogitocorp.com',
    imageUrl: 'https://picsum.photos/seed/cogito/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Intelligence', 'AI'],
  },
  {
    id: '130',
    name: 'Cresta',
    description: 'AI-powered real-time intelligence and automation for contact center teams.',
    websiteUrl: 'https://cresta.com',
    imageUrl: 'https://picsum.photos/seed/cresta/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Automation', 'AI'],
  },
  {
    id: '131',
    name: 'Observe.ai',
    description: 'AI-powered conversation intelligence platform for contact center teams.',
    websiteUrl: 'https://www.observe.ai',
    imageUrl: 'https://picsum.photos/seed/observe/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Intelligence', 'AI'],
  },
  {
    id: '132',
    name: 'Uniphore',
    description: 'AI-powered conversational automation platform for customer engagement.',
    websiteUrl: 'https://www.uniphore.com',
    imageUrl: 'https://picsum.photos/seed/uniphore/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Automation', 'AI'],
  },
  {
    id: '133',
    name: 'ASAPP',
    description: 'AI-powered customer experience platform for automated support and intelligence.',
    websiteUrl: 'https://www.asapp.com',
    imageUrl: 'https://picsum.photos/seed/asapp/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '134',
    name: 'Level AI',
    description: 'AI-powered customer service platform for automated support and intelligence.',
    websiteUrl: 'https://thelevel.ai',
    imageUrl: 'https://picsum.photos/seed/levelai/400/200',
    category: 'Chatbot',
    pricingModel: 'Paid',
    tags: ['Service', 'Support', 'AI'],
  },
  {
    id: '135',
    name: 'MaestroQA',
    description: 'AI-powered quality assurance platform for customer service teams.',
    websiteUrl: 'https://www.maestroqa.com',
    imageUrl: 'https://picsum.photos/seed/maestroqa/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Service', 'QA', 'AI'],
  },
  {
    id: '136',
    name: 'Klaus',
    description: 'AI-powered quality assurance platform for customer service teams.',
    websiteUrl: 'https://www.klausapp.com',
    imageUrl: 'https://picsum.photos/seed/klaus/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Service', 'QA', 'AI'],
  },
];

export const CATEGORIES = Array.from(new Set(TOOLS_DB.map((t) => t.category)));
