import { Tool } from '../types';

export const TOOLS_DB: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    description: 'Advanced AI language model for conversation, coding, and content creation.',
    websiteUrl: 'https://chat.openai.com',
    imageUrl: 'https://picsum.photos/seed/chatgpt/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Chat', 'Writing', 'Coding'],
  },
  {
    id: '2',
    name: 'Midjourney',
    description: 'High-quality AI image generation from natural language descriptions.',
    websiteUrl: 'https://www.midjourney.com',
    imageUrl: 'https://picsum.photos/seed/midjourney/400/200',
    category: 'Image Generation',
    pricingModel: 'Paid',
    tags: ['Art', 'Design', 'Images'],
  },
  {
    id: '3',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that helps you write code faster with less work.',
    websiteUrl: 'https://github.com/features/copilot',
    imageUrl: 'https://picsum.photos/seed/copilot/400/200',
    category: 'Coding',
    pricingModel: 'Paid',
    tags: ['Programming', 'Development', 'AI'],
  },
  {
    id: '4',
    name: 'Jasper',
    description: 'AI content platform that helps teams create high-quality content faster.',
    websiteUrl: 'https://www.jasper.ai',
    imageUrl: 'https://picsum.photos/seed/jasper/400/200',
    category: 'Copywriting',
    pricingModel: 'Paid',
    tags: ['Marketing', 'Writing', 'Business'],
  },
  {
    id: '5',
    name: 'Luma Dream Machine',
    description: 'Generate high-quality, realistic videos from text and images.',
    websiteUrl: 'https://lumalabs.ai/dream-machine',
    imageUrl: 'https://picsum.photos/seed/luma/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Animation', 'AI'],
  },
  {
    id: '6',
    name: 'ElevenLabs',
    description: 'The most realistic AI speech software, perfect for creators and publishers.',
    websiteUrl: 'https://elevenlabs.io',
    imageUrl: 'https://picsum.photos/seed/elevenlabs/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Voice', 'Audio', 'TTS'],
  },
  {
    id: '7',
    name: 'Claude',
    description: 'Next-generation AI assistant for your tasks, no matter the scale.',
    websiteUrl: 'https://claude.ai',
    imageUrl: 'https://picsum.photos/seed/claude/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Chat', 'Analysis'],
  },
  {
    id: '8',
    name: 'Perplexity AI',
    description: 'AI-powered search engine that provides direct answers with citations.',
    websiteUrl: 'https://www.perplexity.ai',
    imageUrl: 'https://picsum.photos/seed/perplexity/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'Research', 'AI'],
  },
  {
    id: '9',
    name: 'Descript',
    description: 'Simple, powerful, and fun way to edit videos and podcasts.',
    websiteUrl: 'https://www.descript.com',
    imageUrl: 'https://picsum.photos/seed/descript/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Editing', 'Podcast', 'Audio'],
  },
  {
    id: '10',
    name: 'Cursor',
    description: 'The AI Code Editor. Built for pair programming with AI.',
    websiteUrl: 'https://cursor.sh',
    imageUrl: 'https://picsum.photos/seed/cursor/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['IDE', 'Coding', 'AI'],
  },
  {
    id: '11',
    name: 'Suno',
    description: 'Create high-quality music and songs with AI in any style.',
    websiteUrl: 'https://suno.com',
    imageUrl: 'https://picsum.photos/seed/suno/400/200',
    category: 'Audio',
    pricingModel: 'Freemium',
    tags: ['Music', 'Audio', 'AI'],
  },
  {
    id: '12',
    name: 'Canva Magic Studio',
    description: 'AI-powered design tools to help you create stunning visuals effortlessly.',
    websiteUrl: 'https://www.canva.com/magic-studio',
    imageUrl: 'https://picsum.photos/seed/canva/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'Graphics', 'AI'],
  },
  {
    id: '13',
    name: 'Grammarly',
    description: 'AI writing assistant that helps you write clearly and effectively.',
    websiteUrl: 'https://www.grammarly.com',
    imageUrl: 'https://picsum.photos/seed/grammarly/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'Editing', 'AI'],
  },
  {
    id: '14',
    name: 'Notion AI',
    description: 'AI-powered workspace that helps you write, plan, and organize.',
    websiteUrl: 'https://www.notion.so/product/ai',
    imageUrl: 'https://picsum.photos/seed/notion/400/200',
    category: 'Productivity',
    pricingModel: 'Paid',
    tags: ['Notes', 'Planning', 'AI'],
  },
  {
    id: '15',
    name: 'Runway Gen-3 Alpha',
    description: 'Advanced AI video generation model for high-fidelity creative control.',
    websiteUrl: 'https://runwayml.com',
    imageUrl: 'https://picsum.photos/seed/runway/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'Art', 'AI'],
  },
  {
    id: '16',
    name: 'Leonardo.ai',
    description: 'Create production-quality visual assets for your projects with AI.',
    websiteUrl: 'https://leonardo.ai',
    imageUrl: 'https://picsum.photos/seed/leonardo/400/200',
    category: 'Image Generation',
    pricingModel: 'Freemium',
    tags: ['Art', 'Images', 'AI'],
  },
  {
    id: '17',
    name: 'Gamma',
    description: 'A new medium for presenting ideas, powered by AI.',
    websiteUrl: 'https://gamma.app',
    imageUrl: 'https://picsum.photos/seed/gamma/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Presentations', 'Design', 'AI'],
  },
  {
    id: '18',
    name: 'Poe',
    description: 'Fast, helpful AI chat interface for multiple models.',
    websiteUrl: 'https://poe.com',
    imageUrl: 'https://picsum.photos/seed/poe/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['Chat', 'AI', 'Models'],
  },
  {
    id: '19',
    name: 'Stable Diffusion',
    description: 'Open-source AI image generation for high-quality visuals.',
    websiteUrl: 'https://stability.ai',
    imageUrl: 'https://picsum.photos/seed/stablediffusion/400/200',
    category: 'Image Generation',
    pricingModel: 'Free',
    tags: ['Art', 'Open Source', 'AI'],
  },
  {
    id: '20',
    name: 'Otter.ai',
    description: 'AI meeting assistant that records audio, writes notes, and captures slides.',
    websiteUrl: 'https://otter.ai',
    imageUrl: 'https://picsum.photos/seed/otter/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Transcription', 'Meetings', 'AI'],
  },
  {
    id: '21',
    name: 'Gemini',
    description: "Google's most capable AI model, built to be multimodal from the ground up.",
    websiteUrl: 'https://gemini.google.com',
    imageUrl: 'https://picsum.photos/seed/gemini/400/200',
    category: 'Chatbot',
    pricingModel: 'Freemium',
    tags: ['AI', 'Google', 'Multimodal'],
  },
  {
    id: '22',
    name: 'DALL-E 3',
    description: 'OpenAI\'s latest image generation system that understands significantly more nuance.',
    websiteUrl: 'https://openai.com/dall-e-3',
    imageUrl: 'https://picsum.photos/seed/dalle/400/200',
    category: 'Image Generation',
    pricingModel: 'Paid',
    tags: ['Art', 'Images', 'OpenAI'],
  },
  {
    id: '23',
    name: 'Adobe Firefly',
    description: 'Generative AI made for creators, integrated directly into Adobe Creative Cloud.',
    websiteUrl: 'https://www.adobe.com/firefly',
    imageUrl: 'https://picsum.photos/seed/firefly/400/200',
    category: 'Image Generation',
    pricingModel: 'Freemium',
    tags: ['Design', 'Adobe', 'Images'],
  },
  {
    id: '24',
    name: 'Replit Ghostwriter',
    description: 'AI-powered coding assistant integrated directly into the Replit IDE.',
    websiteUrl: 'https://replit.com/ai',
    imageUrl: 'https://picsum.photos/seed/replit/400/200',
    category: 'Coding',
    pricingModel: 'Paid',
    tags: ['Coding', 'IDE', 'Development'],
  },
  {
    id: '25',
    name: 'Copy.ai',
    description: 'AI platform for generating high-quality marketing copy and content.',
    websiteUrl: 'https://www.copy.ai',
    imageUrl: 'https://picsum.photos/seed/copyai/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Marketing', 'Writing', 'Business'],
  },
  {
    id: '26',
    name: 'Sora',
    description: 'OpenAI\'s text-to-video model that can create realistic and imaginative scenes.',
    websiteUrl: 'https://openai.com/sora',
    imageUrl: 'https://picsum.photos/seed/sora/400/200',
    category: 'Video',
    pricingModel: 'Paid',
    tags: ['Video', 'OpenAI', 'Realistic'],
  },
  {
    id: '27',
    name: 'HeyGen',
    description: 'Create professional AI videos with talking avatars in minutes.',
    websiteUrl: 'https://www.heygen.com',
    imageUrl: 'https://picsum.photos/seed/heygen/400/200',
    category: 'Video',
    pricingModel: 'Freemium',
    tags: ['Video', 'Avatars', 'Marketing'],
  },
  {
    id: '28',
    name: 'Adobe Podcast',
    description: 'AI-powered audio recording and editing, all in the web browser.',
    websiteUrl: 'https://podcast.adobe.com',
    imageUrl: 'https://picsum.photos/seed/adobepodcast/400/200',
    category: 'Audio',
    pricingModel: 'Free',
    tags: ['Audio', 'Podcast', 'Editing'],
  },
  {
    id: '29',
    name: 'You.com',
    description: 'The AI search engine that gives you control over your search experience.',
    websiteUrl: 'https://you.com',
    imageUrl: 'https://picsum.photos/seed/youcom/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'AI', 'Privacy'],
  },
  {
    id: '30',
    name: 'Microsoft Copilot',
    description: 'Your everyday AI companion, integrated across Microsoft 365 and Windows.',
    websiteUrl: 'https://copilot.microsoft.com',
    imageUrl: 'https://picsum.photos/seed/mscopilot/400/200',
    category: 'Productivity',
    pricingModel: 'Freemium',
    tags: ['Productivity', 'Microsoft', 'Business'],
  },
  {
    id: '31',
    name: 'Brave Search',
    description: 'Privacy-focused search engine with AI-powered summaries and answers.',
    websiteUrl: 'https://brave.com/search',
    imageUrl: 'https://picsum.photos/seed/brave/400/200',
    category: 'Search',
    pricingModel: 'Free',
    tags: ['Search', 'Privacy', 'AI'],
  },
  {
    id: '32',
    name: 'Phind',
    description: 'The AI search engine for developers. Get answers to technical questions instantly.',
    websiteUrl: 'https://www.phind.com',
    imageUrl: 'https://picsum.photos/seed/phind/400/200',
    category: 'Search',
    pricingModel: 'Freemium',
    tags: ['Search', 'Coding', 'Technical'],
  },
  {
    id: '33',
    name: 'Figma AI',
    description: 'AI-powered design features to help you design faster and better in Figma.',
    websiteUrl: 'https://www.figma.com/ai',
    imageUrl: 'https://picsum.photos/seed/figma/400/200',
    category: 'Design',
    pricingModel: 'Freemium',
    tags: ['Design', 'UI/UX', 'Figma'],
  },
  {
    id: '34',
    name: 'Microsoft Designer',
    description: 'Create stunning designs and images in a flash with AI.',
    websiteUrl: 'https://designer.microsoft.com',
    imageUrl: 'https://picsum.photos/seed/msdesigner/400/200',
    category: 'Design',
    pricingModel: 'Free',
    tags: ['Design', 'Graphics', 'Microsoft'],
  },
  {
    id: '35',
    name: 'Tabnine',
    description: 'AI assistant for software developers. Code faster with AI-powered completions.',
    websiteUrl: 'https://www.tabnine.com',
    imageUrl: 'https://picsum.photos/seed/tabnine/400/200',
    category: 'Coding',
    pricingModel: 'Freemium',
    tags: ['Coding', 'Autocomplete', 'AI'],
  },
  {
    id: '36',
    name: 'Writesonic',
    description: 'AI writing tool for creating SEO-friendly content for blogs, ads, and more.',
    websiteUrl: 'https://writesonic.com',
    imageUrl: 'https://picsum.photos/seed/writesonic/400/200',
    category: 'Copywriting',
    pricingModel: 'Freemium',
    tags: ['Writing', 'SEO', 'Marketing'],
  },
];

export const CATEGORIES = Array.from(new Set(TOOLS_DB.map((t) => t.category)));
